import pytz,datetime
year = int(input())
month = int(input())
day = int(input())
hour = int(input())
minute = int(input())
a = datetime.datetime(year,month,day,hour,minute)
cario = pytz.timezone('Africa/Cairo')
london = pytz.timezone('UTC')
delhi = pytz.timezone('Asia/Kolkata')
sydney = pytz.timezone('Australia/Sydney')
tokyo = pytz.timezone('Japan')
seoul = pytz.timezone('Japan')

cario_time = pytz.utc.localize(a).astimezone(cario)
london_time = pytz.utc.localize(a).astimezone(london)
delhi_time = pytz.utc.localize(a).astimezone(delhi)
sydney_time = pytz.utc.localize(a).astimezone(sydney)
tokyo_time = pytz.utc.localize(a).astimezone(tokyo)
seoul_time = pytz.utc.localize(a).astimezone(seoul)

print('Cairo Time is',cario_time.isoformat())
print('London Time is',london_time.isoformat())
print('New Delhi Time is',delhi_time.isoformat())
print('Sydney Time is',sydney_time.isoformat())
print('Tokyo Time is',tokyo_time.isoformat())
print('Seoul Time is',seoul_time.isoformat())